### PR TITLE
Make sure component init event handlers are not unbound

### LINKED ISSUE #1623: Event handlers attached on Component's init (event) are not called.
The issue is replicated here http://jsbin.com/fucabiyade/1/edit?js,console,output

Basically if you do something like:

```javascript
can.Component.extend({
  tag: 'app-foo',
  events: {
    init: function(){
      this.on(window, 'click', 'doSomething');
    },
    doSomething: function(){
    }
  }
})
```

`doSomething` won't be called if you click around, it does work if the event handler is attached on the `inserted` event, or if you do (a more idiomatic way I think) `{window} click: 'doSomething'`. This used to work before CanJS 2.2, probably a regression?

### PR DESCRIPTION
**Pull request by daffl**
Closes #1623 which was caused by a regression introduced in #1422 (fix for issue #1415) calling `this._control.on()` removed all event handlers set up during `init`. Now we just pass a function to the Component control that will be called at the right time in `destroy`.

### CODE REVIEW

File: component/component.js [hunk 1]
```diff
@@ -478,6 +465,11 @@ steal("can/util", "can/view/callbacks","can/view/elements.js","can/control", "ca
 			// Call `can.Control.prototype.off` function on this instance to cleanup the bindings.
 			can.Control.prototype.off.apply(this, arguments);
 			this._bindings.readyComputes = {};
+		},
+		destroy: function() {
+			if(typeof this.options.destroy === 'function') {
```
Comment (justinbmeyer) [inline component/component.js]: Is there a case where this.options.destroy would not be a function?
