### PR TITLE
Switch helper: get expression data in switch

### LINKED ISSUE #1857: switch/case might not work when nested
@daffl ran into a bug when putting together the guide.

### PR DESCRIPTION
**Pull request by matthewp**
This fixes #1857. The bug was that if the expression passed into switch
changed the switch helepr would not re-evaluate and instead on the
switches would re-evaluate. So you could never go from one case to the
default. This fixes it by setting up the binding to the expression
within the switch helper function, so that if the expression changes it
will reevaluate the entire switch.

### CODE REVIEW

File: view/stache/mustache_helpers.js [hunk 1]
```diff
@@ -150,10 +150,11 @@ steal("can/util", "./utils.js","can/view/live",function(can, utils, live){
 			};
 		},
 		'switch': function(expression, options){
+			var expressionValue = resolve(expression);
 			var found = false;
 			var newOptions = options.helpers.add({
 				case: function(value, options){
-					if(resolve(expression) === resolve(value)) {
+					if(!found && expressionValue === resolve(value)) {
```
Comment (daffl) [inline view/stache/mustache_helpers.js]: Did we decide to leave `!found` in?

Comment (matthewp) [inline view/stache/mustache_helpers.js]: I don't know, I did because it seemed like if a case is already found at this point there is no reason to evaluate the value here. We can still talk about it though.
